<?php
/**
 * ItemDraftResponseTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Ebay\Sell\Listing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Listing API
 *
 * Note: This is a (Limited Release) API available only to select developers approved by business units. Enables a seller adding an ad or item on a Partner's site to automatically create an eBay listing draft using the item details from the Partner's site.
 *
 * The version of the OpenAPI document: v1_beta.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ebay\Sell\Listing\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ItemDraftResponseTest Class Doc Comment
 *
 * @category    Class
 * @description The type that defines the field for the &lt;b&gt; createItemDraft&lt;/b&gt; response.
 * @package     Ebay\Sell\Listing
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ItemDraftResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ItemDraftResponse"
     */
    public function testItemDraftResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "item_draft_id"
     */
    public function testPropertyItemDraftId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sell_flow_native_uri"
     */
    public function testPropertySellFlowNativeUri()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sell_flow_url"
     */
    public function testPropertySellFlowUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
